name: Fetch Kaggle Dataset

on:
  schedule:
    # Runs at 6:05 AM UTC on April 5, 2024
    - cron: '30 6 4 4 *'

jobs:
  fetch-dataset:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install Kaggle CLI
      run: pip install kaggle
    - name: Configure Kaggle API Credentials
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        mkdir ~/.kaggle
        echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
    - name: Download Dataset
      run: kaggle datasets download -d mikolajbabula/disaster-images-dataset-cnn-model --path ./data --unzip
    - name: Commit and Push Dataset
      run: |
        git config --global user.email "jamshaidiqbal120@gmail.com"
        git config --global user.name "Jamshaid"
        git add data/*
        git commit -m "Fetch and update Kaggle dataset"
        git push
